#
# LuaDist Travis-CI Hook
#

# We assume C build environments
language: C
	
# Try using multiple Lua Implementations
env:
  - TOOL=""                     # Use native compiler (GCC usually)
  - COMPILER="clang"            # Use clang
  - TOOL="i686-w64-mingw32"     # 32bit MinGW
  - TOOL="x86_64-w64-mingw32"   # 64bit MinGW
  - TOOL="arm-linux-gnueabihf"  # ARM hard-float (hf), linux

# Crosscompile builds may fail
matrix:
  allow_failures:
    - env: TOOL="i686-w64-mingw32"
    - env: TOOL="x86_64-w64-mingw32"
    - env: TOOL="arm-linux-gnueabihf"
  
# Install dependencies
install:
  - git clone git://github.com/LuaDist/_util.git ~/_util
  - ~/_util/travis install

# Bootstap
before_script:
  - ~/_util/travis bootstrap

# Build the module
script:
  - ~/_util/travis build

# Execute additional tests or commands
#after_script:
#  - ~/_util/travis test

# Only watch the master branch
branches:
  only:
    - master

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always